---
name: Build
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo snap install typst
      - name: check out repo code
        uses: actions/checkout@v5
      - name: setup pages
        uses: actions/configure-pages@v5
      - name: build
        run: |
          typst compile doc.typ --font-path=. slide{0p}.svg
          cp inkscape.svg slide3.svg
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
